name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lparsym/requirements.txt
        npm install
    - name: Build
      run: |
        npm run render
        npm run build
    - name: Deploy
      run: |
        git config user.email "endremborza@users.noreply.github.com"
        git config user.name "CI/CD"
        git add docs
        git commit -m "ci-rebuild"
        git push
